services:
  web:
    build:
      context: ./next-web
      target: production
    ports:
      - "3000:3000"
    volumes:
      - ./next-web:/app
      - /app/node_modules
    env_file: ./next-web/.env.production.local
    depends_on:
      server:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  server:
    build:
      context: ./nest-server
      target: production
    volumes:
      - ./nest-server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file: ./next-web/.env.production.local
    command: >
      sh -c "pnpm prisma generate &&
             pnpm prisma migrate deploy &&
             pnpm run seed &&
             pnpm run start:dev"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - app-network

volumes:
  pg_data:
  redis-data:
    driver: local

networks:
  app-network: