services:
  server:
    build:
      context: ./nest-server
      target: development
    volumes:
      - ./nest-server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: ./nest-server/.env.development.local
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "arcane",
            "PassFile": "/config/pgpass"
          }
        }
      }

  pgadmin-pgpass:
    content: |
      postgres:5432:*:arcane:1234

volumes:
  pg_data: