import type {Metadata} from "next";
import {Geologica, Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";

const geologica = Geologica({
  subsets: ["latin", "cyrillic"],
  variable: "--font-geologica",
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Meeting Room Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="uk"
      suppressHydrationWarning
      className={`${geologica.variable} ${inter.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col h-full">
    <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
